// import "./javascript-fundamentals/biggestWord.js";
// import "./javascript-fundamentals/califications.js";
// import "./javascript-fundamentals/checkArguments.js";
// import "./javascript-fundamentals/cloneMerge.js";
// import "./javascript-fundamentals/deepEqual.js";
// import "./javascript-fundamentals/dices.js";
// import "./javascript-fundamentals/hoisting.js";
// import "./javascript-fundamentals/includes.js";
// import "./javascript-fundamentals/primes.js";
// import "./javascript-fundamentals/readBook.js";
// import "./javascript-fundamentals/reverseText.js";
// import "./javascript-fundamentals/values.js";
// import "./javascript-fundamentals/zzcrypt.js";
// import "./javascript-esnext/args.js";
// import "./javascript-esnext/arrayOperations.js";
// import "./javascript-esnext/concat.js";
// import "./javascript-esnext/console.js";
import "./Deliverables/head.js";
import "./Deliverables/tail.js";
import "./Deliverables/init.js";
import "./Deliverables/last.js";
import "./Deliverables/concat.js";
import "./Deliverables/cloneMerge.js";
import "./Deliverables/readBook.ts";